server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/C:\Users\Sion\Desktop\Files\DB\h2\database
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.tutorial.userservice: DEBUG


#token:
#  secret: user_token
#  expiration_time: 86400000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
