server:
  port: 9999

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\Sion\Desktop\Files\Workspace\Project\E-commerce\config-files